# Generated by Django 3.2.7 on 2021-09-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contact_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='contact',
        ),
    ]
